language: python

python:
- 3.8
- 3.7
- 3.6

before_install:
- pip install --upgrade pip
- pip install coveralls
- pip uninstall pytest --yes
- pip install -r test-requirements.txt

install:
- pip install .
- owm clone https://github.com/openworm/OpenWormData.git --branch 'openworm/owmeta#462-owmeta-core-split'

script:
- ./ci-test.sh

after_script:
- coveralls

after_success:
- ./codespeed-submit.sh

env:
  global:
  - secure: Qt0b8NlTnB2FxwdmlXL9/RLcDNA6gUx6+xriipLIZuv+n0rjUmovgqT1UfHGsIUl6pFUXKA8ywPoD2znd3GfigWs/VrB6fXgJiNVNPq1bx1xbX9sPl/6xw5wcVA8nDfFVMj5Q8I5qECaxUwXR83LiKrTCRGewNCRxgGj7aLiYso=
  - secure: YAH6uIq7iO/ufKMUyN3xpKjDqvrJ2yFXmUi7txYaKfqfN+5fW3H/GbnTFXiRVfmNU52c6PlXtcYzllzkJZY0UTkSqt8amMbHyS52JdLhJwMcch4ddDEd0NllMH7XCmGtfqN0E3EF4yHP4EnXqO/HV1VRmwCDRHHMn8c0rl/iqXc=
  - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
