name: Dev Test/Deploy

on:
  push: {}
  pull_request:
    branches: dev

jobs:
  test:
    uses: openworm/owmeta/.github/workflows/test.yml@github-workflows
    with:
      coveralls: ${{github.event_name != 'schedule'}}
      ref: ${{ github.ref }}
    secrets:
      github_token: ${{secrets.GITHUB_TOKEN}}
      pubmed_api_key: ${{secrets.PUBMED_API_KEY}}

  coveralls:
    if: github.event_name == 'push'
    needs: test
    uses: openworm/owmeta/.github/workflows/coveralls-upload.yml@github-workflows
    secrets:
      github_token: ${{secrets.GITHUB_TOKEN}}

