name: Build master

on:
  schedule:
    - cron:  '13 2 10,23 * *'

jobs:
  test:
    uses: openworm/owmeta/.github/workflows/test.yml@github-workflows
    with:
      ref: refs/heads/master
    secrets:
      pubmed_api_key: ${{secrets.PUBMED_API_KEY}}
